### ISSUE TITLE
how to map a nested pojo

### ISSUE THREAD

**Issue by geosmart** [flipkart-incubator/hbase-object-mapper#1]
I have a User Entity ,and User have a UserDetail  ,I want to seprate  them

``` java
@HBTable("User")
public class User implements HBRecord {
    @HBRowKey
    private String id;
    @HBColumn(family = "user", column = "name")
    private String name;
    @HBColumn(family = "user", column = "email")
    private String email;
    @HBColumn(family = "user", column = "password")
    private String password;

      //just familyColumn,   detail Columns  in Another class
    @HBColumn(family = "detail", column = "")
    private UserDetail  detail; 

    @Override
    public String composeRowKey() {
        return id;
    }

    @Override
    public void parseRowKey(String rowKey) {
        this.id = rowKey;
    }
}
```

detail Columns  in Another class

``` java

public class UserDetail{ 
    @HBColumn(family = "detail", column = "address")
    private String address;
    @HBColumn(family = "detail", column = "photo")
    private String photo;
}
```

can you give me some advice? thanks

**Comment by m-manu** [comment]
@geosmart I see that you intend to keep two columns `address` and `photo` (under the same family `detail`) in separate class. Currently, nested POJOs are not supported. 

However, if you're ok with it, you can try either of the 2 alternatives:
- Annotate fields in `UserDetail` class with `JsonProperty` so that you can use it as below:

``` java
@HBColumn(family = "user", column = "detail")
private UserDetail  detail; 
```

(as you know, above will serialize the `UserDetail` object into a JSON string with column name `detail`
- Move `address` and `photo` to `User` class (call it `UserRaw` or something). You can create a class `User` that acts as a wrapper class around `UserRaw` class that has the desired subclasses like `User.Details` etc

**Comment by geosmart** [comment]
Thankyou,as your answer, finally I have move the nested POJO as Json property
