### ISSUE TITLE
Closing the HBASE connection

### ISSUE THREAD

**Issue by sauravbiswasiupr** [flipkart-incubator/hbase-object-mapper#3]
Is there an explicit way to close the connection to HBASE provided in the library. Say I want to create a DAOManager which manages a bunch of HBaseDAOs for different tables. I would like a centralized mechanism to explicitly release the connection pool. What is the best way to do that ?

**Comment by m-manu** [comment]
@sauravbiswasiupr You may use `getHBaseTable()` method on your DAO class to get instance of the underlying `HTable` class. On objects of `HTable` class, you may class `close()`.

Do you have a specific need to do that? e.g. do you intend to use your own connection pool instead of implicitly using HBase's `HConnection`?

**Comment by m-manu** [comment]
@sauravbiswasiupr If you see a generic use-case, please feel free to create an enhancement request. I'm closing this, as I've answered your question.

**Comment by m-manu** [comment]
In the newly released [v1.6](../releases/tag/v1.6), `AbstractHBDAO` implements the `Closeable` interface. So, you can use your DAO classes in try-with-resources (Closing of the resource happens automatically)
